return {
	{
		"folke/which-key.nvim",
		event = "VeryLazy",
		opts = {
			preset = "helix",
			delay = 0,
			defaults = {},
			show_help = true,
			spec = {
				-- individual keymaps
				{ "<leader>q", name = "Save & Quit", hidden = true },
				{ "<leader>Q", name = "Quit without save", hidden = true },
				{ "<leader>w", name = "write", hidden = true },
				{ "<leader>W", name = "write all", hidden = true },
				{ "<leader>rt", icon = { icon = "", hl = "MiniIconsRed" } },
				{ "<leader>ta", icon = { icon = "󰱑", hl = "MiniIconsGreen" } },
				{ "<leader>tf", icon = { icon = "󰱑", hl = "MiniIconsGreen" } },
				{ "<leader>K", icon = { icon = "󰋽", hl = "MiniIconsBlue" } },
				{ "<leader>a", icon = { icon = "", hl = "MiniIconsYellow" } },
				{ "<leader>l", icon = { icon = "", hl = "MiniIconsPurple" } },
				{ "<leader>cm", icon = { icon = "󱁤", hl = "MiniIconsGrey" } },
				{ "<leader>e", icon = { icon = "󰨚", hl = "MiniIconsYellow" } },
				{ "<leader>.", icon = { icon = "", hl = "MiniIconsBlue" } },
				{ "<leader><leader>", desc = "Beacon", icon = { icon = "󰞏", hl = "MiniIconsYellow" } },
				-- groups
				{ "<leader>b", group = "Buffer" },
				{ "<leader>c", group = "Code" },
				{ "<leader>f", group = "File/Find" },
				{ "<leader>g", group = "Git" },
				{ "<leader>gh", group = "Hunks" },
				{ "<leader>d", group = "Directory", icon = { icon = "󱧮", hl = "MiniIconsGreen" } },
				{ "<leader>n", group = "Noice" },
				{ "<leader>r", group = "Run", icon = { icon = "", hl = "MiniIconsRed" } },
				{ "<leader>s", group = "Search" },
				{ "<leader>S", group = "Session" },
				{ "<leader>t", group = "Test", icon = { icon = "󰱑", hl = "MiniIconsGreen" } },
				{ "<leader>T", group = "Terminal" },
				{ "<leader>u", group = "UI" },
				{ "<leader>i", group = "Window" },
				{ "<leader>x", group = "Diag/Qckfix", icon = { icon = "󰀩", hl = "MiniIconsRed" } },
				{ "<leader><Tab>", group = "Tab" },
				{ "<leader>?", group = "Funstuff", icon = { icon = "󱁖", hl = "MiniIconsRed" } },
			},
		},
		config = function(_, opts) require("which-key").setup(opts) end,
	},
}
